dist: trusty
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
bash
notifications:
  slack:
    rooms:
      secure:
THf3gk8ALzZe2739Ycuy2Si9q596Jbbmic3ncmn98U2bmHysq5VYuvO/xyCs++C9VxGjOl9bAmUUF0AuC5WULz213qoY75VoZctApLlSlZpiyXyQ8Q1NEhj4kv8X6+GTv2ENvA2cSmr78rwwSd6SOtlm2UnnwTuvzMazcaPclsGD+hCV7rljnwvmibNt043hIwq5+Im+pwJcDqGOtnffePfZPdZFJH3e/nwa3wa9y3cYET3LnGN0WFPRdwuVVxNKB7rEokEvO1HTxpUhGcWLcOsPl+vFT98t53tNAPPhC2Z/C8nyLwTfg1B11yO5+wz7ci5WjMUqxlOsWSS4tq55k8wjCk2/tyqAY9FdHr+sBwH4G0nRqDWEVz9+xgmQRH03fbNUs8etnknu87dlQpd28RyvtqhthRmnq6detj5lmJ5FI6wQzlyeOPegZ+8o9cns/NWqoutGAFTaLaD1xSRHOtQxhbIyOapcabHeG/5GsQEW/dl8wNVcKp71mv3MpkD5JZqy/r4ll3YXsFiAXJsuEtg12zm+QGZ0hQMn7eVqm6BpIK8rv86N++Ds5I8/GXPeDxcuV8yR//ukEcZ1/0ORCqqyhznHzpE56v15LndQR5m9VorH+0q83c6zyMtJkp3vHlMUtdnzCdrGxUTBw301bAL7nd6z3F+y/XPC0WnPL0c=
