---
- name: Add Mongo packages repo
  apt_key:
    id: "EA312927"
    keyserver: keyserver.ubuntu.com
    state: present
  tags: install

- name: add repo mongo
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  tags: install

- name: install packages
  apt:
    pkg: mongodb-org
    state: present
    allow_unauthenticated: yes
  tags: install

- name: enable mongo
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: install
