- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install Rubi package
  apt: "name={{ item }} state=present"
  with_items:
    - ruby-full
    - ruby-bundler
    - build-essential
  tags: ruby
